Iter5
physicist2018/url-shortener-go pull request #5
Opened 2024-12-31 02:24 UTC by physicist2018

Add config via env variables

2025-01-09 20:38 UTC, i-am-megashchik commented
Добавь меня еще в ревьюеры

2025-01-10 02:06 UTC, physicist2018 commented
> Добавь меня еще в ревьюеры

Не могу, так как предыдущий запрос ты не принял

2025-01-10 06:37 UTC, physicist2018 commented
Прими запрос в коллаборацию, потом только можно назначить реаьювером23:38, 9 января 2025 г., "i-am-megashchik" ***@***.***>:
Добавь меня еще в ревьюеры

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

2025-01-10 13:47 UTC, i-am-megashchik commented
Ага, я нашел где это
Добавил себя

Поправишь замечания, присылай заново на ревью, апрувну

2025-01-10 15:57 UTC, i-am-megashchik requested changes

2025-01-10 15:57 UTC, megashchik commented on cmd/shortener/main.go
> +	//fmt.Println(config.DefaultConfig)
Лишний комментарий

2025-01-10 15:57 UTC, megashchik commented on internal/randomstring/randomstring.go
> +var rnd = rand.New(rand.NewSource(10))
Хоть это и тестовый проект, но сид лучше брать всегда разный, хотя бы `time.Now().UnixNano()`

2025-01-10 15:57 UTC, megashchik commented on internal/shortener/shortener.go
> +	if r.URL.Path != "/" {
А такое разве возможно?

За эту проверку отвечает сервер

2025-01-10 15:57 UTC, megashchik commented on internal/shortener/shortener.go
> +	if (err != nil) && (err != io.EOF) {
Проверки на конкретные ошибки лучше делать через `errors.Is`

2025-01-10 15:57 UTC, megashchik commented on internal/urlstorage/urlstorage.go
> +	defaultURLStorage = NewURLStorage()
синглтоны и init не самая хорошая практика, лучше явно создавать сервисы в main и прокидывать их везде

2025-01-10 15:57 UTC, megashchik commented on internal/urlstorage/urlstorage.go
> +func SetDefaultURLStorage(s *URLStorage) {
Не используется

2025-01-10 15:57 UTC, megashchik commented on internal/urlstorage/urlstorage.go
> +		if v.LongURL == longURL {
поиск по слайсу достаточно долгий, особенно, что чаще всего потребуется искать данные из последних добавленных элементов, а по ним мы будем сравнивать в конце

2025-01-10 15:57 UTC, megashchik commented on internal/urlstorage/urlstorage.go
> +	return "", errors.New(ShortURLNotFound)
Ошибки лучше создавать заранее, а при необходимости ссылаться на предопределенные

2025-01-10 15:57 UTC, megashchik commented on internal/urlstorage/urlstorage.go
> +	ShortURLCreated        = "ссылка создана успешно"
Почему часть констант приватные, а часть публичные?

2025-01-10 15:57 UTC, megashchik commented on internal/urlstorage/urlstorage.go
> +	ShortURLCreated        = "ссылка создана успешно"
Эта строка не используется

2025-01-10 15:57 UTC, megashchik commented on internal/shortener/shortener.go
> +	fmt.Println(shortURL)
Println в финальном коде не должен быть

2025-01-10 15:57 UTC, megashchik commented on internal/shortener/shortener.go
> +	if longURL, err := urlstorage.GetDefaultURLStorage().GetLongURL(shortURL); err == nil {
Более принято обрабатывать сначала ошибочные варианты, после которых следует выход

2025-01-10 15:57 UTC, megashchik commented on internal/shortener/shortener.go
> +	if shortURL, err := urlstorage.GetDefaultURLStorage().CreateShortURL(url); err == nil {
Необходимо пользоваться объектом-зависимостью, вместо использования синглтона

2025-01-10 15:57 UTC, megashchik commented on internal/shortener/shortener.go
> +			http.Error(w, "", http.StatusBadRequest) // 400
Едва ли текст ошибки должен быть нулевым, лучше сообщать что пошло не так

2025-01-18 09:31 UTC, i-am-megashchik commented on internal/adapters/httphandlers/url_handler.go
> +	if errors.Is(err, nil) && !errors.Is(err, io.EOF) {
Если ошибка является nil и ошибка не является концом чтения

Если она nil, то она по определению не может являться io.EOF

2025-01-18 09:33 UTC, i-am-megashchik commented on internal/adapters/memory/url_repository_map.go
> +func (r *URLRepositoryMap) Save(url *urlmodels.URL) (*urlmodels.URL, error) {
передавать тут по значению было бы лучше, потому что нам не нужно изменять значение и можно лишний раз не создавать ссылку

2025-01-18 09:35 UTC, i-am-megashchik commented on internal/adapters/httphandlers/url_handler.go
> +	fullURL := fmt.Sprintf("%s/%s", h.baseURL, shortURL.Short)
Почему мы формируем строку до обработки ошибки?

2025-01-18 09:36 UTC, i-am-megashchik commented on internal/core/services/url/url_service.go
> +	return s.urlRepo.Save(url)
Если у нас не удалось создать ссылку, самым удобным для пользователя поведением было бы попробовать сделать еще одну короткую ссылку

2025-01-18 09:37 UTC, i-am-megashchik commented on internal/config/config.go
> +		BaseURLServer: "http://localhost:8000",
Мы тут заполняем BaseURLServer, а потом переписываем его во флагах, причем значение тут и во флагах разное

2025-01-18 09:40 UTC, i-am-megashchik commented on internal/adapters/httphandlers/url_handler.go
> +	shortURL, err := h.urlService.GenerateShortURL(originalURL)
Это не shortURL, потому что содержит как которткую, так и оригинальную ссылку

Возвращать достаточно только короткую ссылку

2025-01-18 09:42 UTC, i-am-megashchik commented on pkg/utils/generator.go
> +	rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
Инициализация рандомайзера для каждой создаваемой строки является излишней

2025-01-18 10:42 UTC, physicist2018 commented on internal/adapters/httphandlers/url_handler.go
> +	if errors.Is(err, nil) && !errors.Is(err, io.EOF) {
Вкурил, исправил

2025-01-18 10:45 UTC, physicist2018 commented on internal/adapters/httphandlers/url_handler.go
> +	shortURL, err := h.urlService.GenerateShortURL(originalURL)
поправил наименование, все-таки оставил возврат всей модели

2025-01-18 10:45 UTC, physicist2018 commented on internal/adapters/httphandlers/url_handler.go
> +	fullURL := fmt.Sprintf("%s/%s", h.baseURL, shortURL.Short)
исправио

2025-01-18 10:46 UTC, physicist2018 commented on internal/config/config.go
> +		BaseURLServer: "http://localhost:8000",
Да, верно, достаточно просто создать объект, пофиксил

2025-01-18 10:47 UTC, physicist2018 commented on pkg/utils/generator.go
> +	rnd := rand.New(rand.NewSource(time.Now().UnixNano()))
переделал через интерфейс

2025-01-18 10:57 UTC, physicist2018 commented on internal/adapters/memory/url_repository_map.go
> +func (r *URLRepositoryMap) Save(url *urlmodels.URL) (*urlmodels.URL, error) {
Ок

2025-01-18 11:29 UTC, physicist2018 commented on internal/core/services/url/url_service.go
> +	return s.urlRepo.Save(url)
пофиксил

2025-01-19 23:58 UTC, merged